# Generated by Django 5.1 on 2024-09-02 20:00

import Core.models
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='userticket',
            name='is_transferred',
        ),
        migrations.AddField(
            model_name='userticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userticket',
            name='qrcode',
            field=models.ImageField(blank=True, default=Core.models.UserTicket.generate_qr_code, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-0.1655385435678049,-0.848121657036245', max_length=63),
        ),
    ]
