# Generated by Django 5.1 on 2024-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_ticket_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
